# These are supported funding model platforms

We are really happy to add your name in our sponsor's list.
Please reach out to us on gmail using the id dashashutosh@gmail.com for further discussion.

Thank You
